<?php
echo  '<div class="MenuLateralCerrado">'
    . ' <a href="javascript:void(0)" class="openbtn" onclick="openNav()">&#9776;</a>'
    . ' <br><br><br>'
    . ' <a href="Inicio.php"><img src="Imagenes/Inicio.png";></a>'
    . ' <a href="PlaneacionEstrategica.php" id="PagInicioPE" style="display:none"><img src="Imagenes/NuevoDocumento.png"></a>'
    . ' <a href="Busqueda.php" ><img src="Imagenes/Buscar.png"></a>'
    . ' <a href="Revision.php" id="PagRevision" style="display:none"><img src="Imagenes/Revision.png"></a>'
    . ' <a href="Catalogos.php"><img src="Imagenes/Catalogo.jpg"></a>'
    . ' <a href="Administracion.php" id="PagAdministracion" style="display:none"><img src="Imagenes/BaseDatos.png"></a>'
    . ' <a href="MiPerfil.php"><img src="Imagenes/Perfil.png"></a>'
    . ' <a href="AdministrarUsuarios.php" id="PagUsuarios" style="display:none"><img src="Imagenes/NuevoUsuario.png"></a>'
    . ' <a href="PHPFunciones/CerrarSesion.php"><img src="Imagenes/LogOut.png"></a>'
    . '</div>'
    . '<div class="MenuLateralAbierto">'
    . ' <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>'
    . ' <a href="Inicio.php"><img src="Imagenes/Inicio.png">Inicio</a>'
    . ' <a href="PlaneacionEstrategica.php" id="PagInicioPE2" style="display:none"><img src="Imagenes/NuevoDocumento.png">Documento</a>'
    . ' <a href="Busqueda.php"><img src="Imagenes/Buscar.png">Busqueda</a>'
    . ' <a href="Revision.php" id="PagRevision2" style="display:none"><img src="Imagenes/Revision.png">Revisi&oacute;n</a>'
    . ' <a href="Catalogos.php"><img src="Imagenes/Catalogo.jpg">Informaci&oacute;n</a>'
    . ' <a href="Administracion.php" id="PagAdministracion2" style="display:none"><img src="Imagenes/BaseDatos.png">Administraci&oacute;n</a>'
    . ' <a href="MiPerfil.php"><img src="Imagenes/Perfil.png">Mi Perfil</a>'
    . ' <a href="AdministrarUsuarios.php" id="PagUsuarios2" style="display:none"><img src="Imagenes/NuevoUsuario.png">Usuarios</a>'
    . ' <a href="PHPFunciones/CerrarSesion.php"><img src="Imagenes/LogOut.png">Cerrar Sesi&oacute;n</a>'
    . '</div>';
?>
